--O diretor da Mangojata Advogados ordenou que lhe fosse entregue um relatório sobre seus advogados atuais.

--O diretor quer que você mostre para ele o nome do advogado que têm mais clientes, 
--o nome do advogado que tem menos clientes e a média de clientes entre todos os advogados.

--OBS: Antes de apresentar a média mostre um campo chamado Average a fim de deixar o relatório mais apresentável. 
--A média deverá ser apresentada em inteiros.

IF OBJECT_ID ('TEMPDB.DBO.#LAWYERS','U') IS NOT NULL DROP TABLE #LAWYERS;
IF OBJECT_ID ('TEMPDB.DBO.#ADV_COM_MAIS_CLIENTES','U') IS NOT NULL DROP TABLE #ADV_COM_MAIS_CLIENTES;
IF OBJECT_ID ('TEMPDB.DBO.#ADV_COM_MENOS_CLIENTES','U') IS NOT NULL DROP TABLE #ADV_COM_MENOS_CLIENTES;
IF OBJECT_ID ('TEMPDB.DBO.#MEDIA_ADV','U') IS NOT NULL DROP TABLE #MEDIA_ADV;


CREATE TABLE #LAWYERS(
	[REGISTER] INT,
	[NAME] VARCHAR(155),
	[CUSTOMERS_NUMBER] INT
)

INSERT INTO #LAWYERS ([REGISTER],[NAME],[CUSTOMERS_NUMBER]) VALUES
(1648,'Marty M. Harrison',5),
(2427,'Jonathan J. Blevins',15),
(3365,'Chelsey D. Sanders',20),
(4153,'Dorothy W. Ford',16),
(5525,'Penny J. Cormier',6)


--====================== 1º Opção
SELECT
	L.[NAME],
	L.[CUSTOMERS_NUMBER]
FROM 
	#LAWYERS L
WHERE
	L.[CUSTOMERS_NUMBER] = (SELECT MIN([CUSTOMERS_NUMBER]) FROM #LAWYERS)OR
	L.[CUSTOMERS_NUMBER] = (SELECT MAX([CUSTOMERS_NUMBER]) FROM #LAWYERS)
UNION ALL 
SELECT
	'Average' AS [NAME],	
	AVG([CUSTOMERS_NUMBER]) AS [CUSTOMERS_NUMBER]
FROM	
	#LAWYERS WITH(NOLOCK)


--================== 2 º Opção 

/*CRIANDO TABELAS TEMPORÁRIAS */

CREATE TABLE #ADV_COM_MAIS_CLIENTES(
	[NAME] VARCHAR(155),
	[CUSTOMERS_NUMBER] INT
)

CREATE TABLE #ADV_COM_MENOS_CLIENTES(
	[NAME] VARCHAR(155),
	[CUSTOMERS_NUMBER] INT
)

CREATE TABLE #MEDIA_ADV (
	[NAME] VARCHAR(155),
	[CUSTOMERS_NUMBER] INT
)

/*INSERINDO OS DADOS NAS TABELAS */

INSERT INTO #ADV_COM_MAIS_CLIENTES ([NAME],[CUSTOMERS_NUMBER])
SELECT
	L1.[NAME],
	L1.[CUSTOMERS_NUMBER]
FROM #LAWYERS L1 WHERE L1.[CUSTOMERS_NUMBER] = (SELECT MAX([CUSTOMERS_NUMBER]) FROM #LAWYERS)

INSERT INTO #ADV_COM_MENOS_CLIENTES ([NAME],[CUSTOMERS_NUMBER])
SELECT
	L2.[NAME],
	L2.[CUSTOMERS_NUMBER]
FROM #LAWYERS L2 WHERE L2.[CUSTOMERS_NUMBER] = (SELECT MIN([CUSTOMERS_NUMBER]) FROM #LAWYERS)

INSERT INTO #MEDIA_ADV ([NAME],[CUSTOMERS_NUMBER])
SELECT
	'Average',
	AVG(L3.[CUSTOMERS_NUMBER])
FROM #LAWYERS L3 WITH(NOLOCK)

/*REALIZANDO A CONSULTA PARA TRAZER O RESULTADO ESPERADO */

SELECT * FROM #ADV_COM_MAIS_CLIENTES WITH(NOLOCK)
	UNION ALL
SELECT * FROM #ADV_COM_MENOS_CLIENTES WITH(NOLOCK)
	UNION ALL
SELECT * FROM #MEDIA_ADV WITH(NOLOCK)